# permissions for end users to edit externalsvcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: externalsvc-editor-role
rules:
- apiGroups:
  - mapping.sf.ucloud.cn
  resources:
  - externalsvcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mapping.sf.ucloud.cn
  resources:
  - externalsvcs/status
  verbs:
  - get
