# permissions for end users to view externalsvcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: externalsvc-viewer-role
rules:
- apiGroups:
  - mapping.sf.ucloud.cn
  resources:
  - externalsvcs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mapping.sf.ucloud.cn
  resources:
  - externalsvcs/status
  verbs:
  - get
